name: coaching_institute
description: "A new project by Yash Manghnani"
publish_to: 'none' 

version: 1.0.0+4

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  lottie: ^3.1.2
  stylish_text: ^0.0.1
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  iconly: ^1.0.1
  ionicons: ^0.2.2
  image_picker: ^1.1.1
  fluttertoast: ^8.2.5
  mvc_pattern: ^8.12.0
  http: ^1.2.1
  syncfusion_flutter_calendar: ^25.2.6
  custom_date_range_picker: ^1.1.0
  flutter_quill: ^9.3.21
  intl: ^0.19.0
  loader_overlay: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/lottie/
    - assets/images/
  #   - images/a_dot_ham.jpeg
